### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by akamob** [jrainey12/gait-transformer#1]
Hi, Thank you for the great work.

I want to build a gait analysis framework that detect keypoints of human body and distinguish human identity by analyzing their gait. Could you give me some suggestions to use your code? and is there any papers or tutorials?

Any help is much appreciated:)

**Comment by james-rainey** [comment]
Hi,
This is just a side project I worked on for a while, therefore there is no paper or tutorials for this work. 
In its current state this code is useable for gender classification but isn't set up for full gait recognition.  
This code takes in single gait representation and determines its gender. 
To train this method you need a dataset of GEIs (I used CASIA-B) split by gender into two folders. Then use `train_test_ViT.py` with the data folder and the required parameters to train a model.

A common method for gait recognition is to take in a pair of gait representations (such as GEIs) and determine if they are the same, to do this with this code the input layers would have to be modified to use a Siamese approach to take in two inputs.  
I have used this approach successfully in the past with CNNs but I am unsure how well it would work with a ViT architecture.

[GaitSet](https://github.com/AbnerHqC/GaitSet) is a good gait recognition method that has full source code, it is not ViT based but may be worth looking at for a full gait recognition method.

**Comment by akamob** [comment]
Hi, thank you for your reply.

Ok, I will try to test and if I have some new problems then I would contact you again.

Thank you!
